"""add  qr_code_url to photo

Revision ID: 72710fca2fd8
Revises: ad7793cd6454
Create Date: 2024-12-23 18:15:48.718652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72710fca2fd8"
down_revision: Union[str, None] = "ad7793cd6454"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos", sa.Column("qr_core_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "qr_core_url")
    # ### end Alembic commands ###
