"""Add updated_at-True2 in Table Message

Revision ID: 7b1b2849b979
Revises: 25b7f37d6ea1
Create Date: 2025-03-28 15:32:26.221077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1b2849b979'
down_revision: Union[str, None] = '25b7f37d6ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
